[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
image = "0.24.5" #![feature(anonymous_lifetime_in_impl_trait)]
num-traits = "0.2.15"
tuple-map = "0.4.0"

